# Generated by Django 5.1.3 on 2024-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('Position', models.CharField(choices=[('Manager', 'manager'), ('software developer', 'sde'), ('project leader', 'prleader')], max_length=100)),
                ('about', models.TextField(max_length=200)),
            ],
        ),
    ]
