name: Django CI/CD Pipeline

# Trigger the workflow on push and pull request to the `main` branch
on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Set up the environment to run on the latest Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Specify the Python version to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      # Step 4: Set up database (if you're using SQLite)
      - name: Set up SQLite database
        run: |
          python manage.py migrate  # Run migrations to set up the database

      # Step 5: Run tests
      - name: Run tests
        run: |
          python manage.py test  # Run your Django tests
